@startuml

class Game {
    +{static} create(player1, player2)
    +{static} instance()
    current_turn
    +player1()
    +player2()
    +attack(player=)
    +paralyse(player=)
    +unparalyse(player)
    +switch_turn()
    +other_turn()
    +opponent_of(the_player)
    +game_over?()
    +loser()
}

class Player {
    DEFAULT_HIT_POINTS
    +name
    +hit_points
    +damage_score
    +paralysed
    +receive_damage()
    +a_computer?()
    +try_to_paralyse()
    +paralysed?()
    -random_hit_points_generator()
}

class Model {
    Player
    Game
}

class Controller {
    app.rb
}

class View {
    index
    new_player_form
    game_status
    show-attack
    paralyse-sleep
    game_over
}

Game -> Player :"2" players

Model ->View
View o-> Controller

@enduml
