@startuml

class Game {
    +{static} create(player1, player2)
    +{static} instance()
    current_turn
    +player1()
    +player2()
    +attack(player=)
    +switch_turn()
    +opponent_of(the_player)
    +game_over?()
    +loser()
}

class Player {
    DEFAULT_HIT_POINTS
    name
    hit_points
    +receive_damage()
}

class Model {
    Player
    Game
}

class Controller {
    app.rb
}

class View {
    index
    new_player_form
    play
    attack
    game_over
}

Game -> Player :"2" players

Model ->View
View o-> Controller

@enduml
